#!/usr/bin/bash

# script to generate the params.sv file based on the command line parameters
# usage: ./genParams1 [WIDTH] [ACCW] [PIPELINED]
#    where you will replace [WIDTH] [ACCW] and [PIPELINED] with the desired value of
#    those parameters
#      - WIDTH is the bitwidth of the MAC inputs and of the MAC output
#        (2 <= WIDTH < 32)
#      - ACCW is the bitwidth of the MAC's accumulator
#        (ACCW must be >= 2*WIDTH and <= 80)

# example: for WIDTH=8, ACCW=24, PIPELINED=0, run: ./genParams1 8 24 0

if [ $# -ne 3 ]; then
    echo "ERROR: incorrect number of parameters given."
    echo "Usage: ./genParams1 [WIDTH] [ACCW] [PIPELINED]"
    echo "See comments in genParams1 file for more information"
else
    echo "\`define WIDTHVAL $1" > params.sv
    echo "\`define ACCWVAL $2" >> params.sv
    echo "\`define PIPELINEDVAL $3" >> params.sv
fi
